apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moon-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orcunbalcilar/moon-gitops
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
